name: Blackbird Actions
run-name: Updating Blackbird APIs and mocks
on: [push]
jobs:
  Blackbird-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Update Blackbird APIs and Mocks
        uses: actions/checkout@v4
        env:
          BLACKBIRD_TOKEN: ${{ secrets.BLACKBIRD_TOKEN }}
      - run: |
          echo $BLACKBIRD_TOKEN
          sudo mkdir -p /usr/local/bin
          sudo curl -fL 'https://blackbird.a8r.io/api/download/cli/v1.10.2/linux/amd64' -o /usr/local/bin/blackbird
          sudo chmod a+x /usr/local/bin/blackbird
          blackbird version
          blackbird api list